---
name: Scheduled file updates

on:
  workflow_dispatch:
  schedule:
    # 00:00 UTC is 8am SGT | 12:00 UTC is 8pm SGT
    - cron: '0 0,12 * * *'

env:
  TZ: "Asia/Singapore"
  git_user_email: "github-actions[bot]@users.noreply.github.com"
  git_user_name: "github-actions[bot]"

permissions:
  contents: write

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run bash script
        run: |
          make install
          make update

      - name: Commit and push changes
        run: |
          git config --local user.email ${{ env.git_user_email }}
          git config --local user.name ${{ env.git_user_name }}
          git add -A
          git commit -m "Scheduled file updates: Run update.sh" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
